name: xmpp_plugin
description: Xmpp plugin which helps to connect with xmpp via native channels and native libs like smack android and ios via xmppframework
version: 2.3.0
homepage: https://github.com/vavadiyahiren/xmpp_plugin

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  device_info_plus: ^9.0.2
  permission_handler: ^10.4.1
  path_provider: ^2.0.15
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.xrstudio.xmpp.flutter_xmpp
        pluginClass: FlutterXmppPlugin
      ios:
        pluginClass: FlutterXmppPlugin
